name: Publish to TestPyPI
on:
  push:
    branches: [main]
jobs:
  build-and-publish:
    name: Build and Publish on TestPyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Bump version
        run: |
          poetry version $(poetry version -s).post$(TZ=GMT date "+%Y%m%d%H%M")
      - name: Build and publish
        uses: JRubics/poetry-publish@v1
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
