name: Publish to PyPI
on:
  release:
    types: [published]
jobs:
  build-and-publish:
    name: Build and Publish on TestPyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish
        uses: JRubics/poetry-publish@v1.6
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
